config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :games do
    resources :reviews
  end
  root 'games#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
    belongs_to :user
    has_many :reviews
    validates :title, :publisher, :genre, :platform, :description, :image_file, presence: true
    validates :title, uniqueness: true
    validates :image_file, format: {
        with: %r{\.(jpg|jpeg|png)\Z}i,
        message: 'image extension must be jpg, jpeg or png'
      } 
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :game
    belongs_to :user
    validates :rating, :comment, presence: true
    validates_numericality_of :rating, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5, :message => "Rating must be from 0 to 5"
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  has_many :reviews
  has_secure_password
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all.order("created_at DESC")
  end

  # GET /games/1
  # GET /games/1.json
  def show
    if @game.reviews.blank?
      @average_review = 0
    else
      @average_review = @game.reviews.average(:rating).round(2)
  end
end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :publisher, :genre, :release_date, :platform, :description, :image_file)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_game
    before_action :find_review, only: [:edit, :update, :destroy]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.game_id = @game.id
        @review.user_id = session[:user_id]

        if @review.save
            redirect_to game_path(@game)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to game_path(@game)
        else
            render 'edit'
        end
    end
    
    def destroy
        @review.destroy
        redirect_to game_path(@game)
    end

    private 

        def review_params
            params.require(:review).permit(:rating, :comment)
        end

        def find_game
            @game = Game.find(params[:game_id])
        end

        def find_review
            @review = Review.find(params[:id])
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user
      redirect_to root_path
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end 

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "#{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: "#{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "#{@user.name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for @game do |f| %>
    <%= f.input :title %>
    <%= f.input :publisher %>
    <%= f.input :genre %>
    <%= f.input :release_date %>
    <%= f.input :platform %>
    <%= f.input :description %>
    <%= f.input :image_file %>
    <%= f.button :submit %>
  <% end %>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1 class="page-header" align="center">Games</h1>

<div class="container">
  <% @games.each do |game| %>
    <div class="card text-center border-dark mb-5" >
      
      <div class="card-header bg-info">
        <h2 class="" style="color:white;"><%= game.title%></h2>
      </div>
      
      <div class="card-body">
        <img class="card-img-top" width="400" height="275" src=<%= game.image_file %> alt="Card image cap">
      </div>

      <div class="card-footer text-muted">
        <a href="/games/<%= game.id %>" class="btn btn-block btn-primary"><h3>More Details</h3></a>
      </div>
    </div>

  <% end %>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="container">
<div class="row">
<div class="col-md-4">
  <img src="<%= @game.image_file%>" alt="Image Thumbnail" class="img-thumbnail">

</div>
  <div class="col-md-8">  

    <h2>Title: </h2>
    <h3><%= @game.title %></h3>
    <h2>Publisher: </h2>
    <h3><%= @game.publisher %></h3>
    <h2>Genre: </h2>
    <h3><%= @game.genre %></h3>
    <h2>Released: </h2>
    <h3><%= @game.release_date %></h3>
    <h2>Platform(s): </h2>
    <h3><%= @game.platform %></h3>
    <h2>Average Rating</h2>
    <h3><%= @average_review %> out of 5</h3>
    <h2>Description: </h2>
    <h3><p><%= @game.description %></p></h3>

    <h3><%= link_to 'Back', games_path %></h3>  
    
    <% if session[:user_id] %>
    
      <h3><%= link_to 'Edit Game', edit_game_path(@game) %></h3>   
      <h3><%= link_to 'Delete Game', game_path(@game), method: :delete, data: { confirm: "Are you sure?" } %></h3>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div>
      <% if session[:user_id] %>
        <a href="/games/<%= @game.id %>/reviews/new" class="btn btn-primary"><h3>Add Review</h3></a>
      <% end %>
    </div>
      <h1>User Reviews</h1>
      <%= render @game.reviews %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">  
</head>

<nav class="navbar navbar-expand-md navbar-dark bg-dark" style="position: fixed; top: 0; width: 100%; z-index: 999;">
<h1 style="color:white;">GameReviews</h1>

<div class="collapse navbar-collapse" id="navbarsExampleDefault">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <a class="nav-link" href="/"><h3>Home</h3></a>
    </li>
    <% if session[:user_id] %>
      <li class="nav-item">
        <a class="nav-link" href="/games/new"><h3>Add Game</h3></a>
      </li>
    <% end %>
   </ul>

  
  <ul class="navbar-nav ml-auto">
    <% if session[:user_id] %>
    <li class="nav-item">
      <a class="nav-link"><h3><%= link_to "Logout", logout_path, :method => :delete %><h3></a>
    </li>
      <% else %>
    <li class="nav-item">
      <a class="nav-link" href="/users/new"><h3>Register</h3></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/login"><h3>Login</h3></a>
    <% end %>
    </li>
  </ul>
</div>
</nav>

<p class="notice"><%= notice %></p>

<body style="margin-top: 85px;">

<%= content_tag :body, class: controller.controller_name do %>
  <%= yield %>
<% end %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@game, @game.reviews.build]) do |f|%>
    
    <%= f.input :rating, label: "Rating (out of 5)" %> 
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>    

app/views/reviews/_review.html.erb
<h2>Rating: <%= review.rating %> out of 5</h2>
<h3><p><%= review.comment %></p></h3>

<div>
<% if session[:user_id] %>
    
    <%= link_to "Edit", edit_game_review_path(review.game, review) %> |
    <%= link_to "Delete", game_review_path(review.game, review), method: :delete, data: { confirm: "Are you sure?" } %>

<% end %>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@game, @review]) do |f| %>
    <%= f.input :rating %>
    <%= f.input :comment %>
    <%= f.button :submit %>   
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>